
export const SESSION_NEW = 'SESSION_NEW';
export const SESSION_REMOVE = 'SESSION_REMOVE';

export const KEEPALIVE_PUSH = 'KEEPALIVE_PUSH';
export const KEEPALIVE_POP = 'KEEPALIVE_POP';
export const KEEPALIVE_POP_TO_ROOT = 'KEEPALIVE_POP_TO_ROOT';
export const KEEPALIVE_POP_TO = 'KEEPALIVE_POP_TO';

export const TABBAR_SHOW = 'TABBAR_SHOW';
export const TABBAR_HIDE = 'TABBAR_HIDE';

export const  REFRESH_PAGE_ME_UPDATE = 'REFRESH_PAGE_ME_UPDATE';

export const PAGE_ANIMATION_SET = 'PAGE_ANIMATION_SET';
export const PAGE_ANIMATION_BACK_SET = 'PAGE_ANIMATION_BACK_SET';

export const USER = 'USER';

export const LANG_SAVE = 'LANG_SAVE';
export const LANG_REMOVE = 'LANG_REMOVE';
